# Generated by Django 5.0.1 on 2024-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_created_at_remove_game_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
